name: assigment
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  http: ^1.2.2
  html: ^0.15.0

flutter_native_splash:
          color: "#ffffff"
          image: assets/splash.png
          color_dark: "#121212"
          image_dark: assets/splash.png
        

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/splash.png
    - assets/background.jpg
